display_name: NTUT Program Assignment
package_name: ntut-program-assignment

icon: assets/icon@x500.png
summary: A beautiful homework assign system for NTUT CS students
group: Applications/Development Tools
vendor: YFHD
packager: YFHD
packagerEmail: yfhdtw@gmail.com
license: MIT
url: https://github.com/YFHD-osu/NTUT-Program-Assignment

maintainer:
  name: YFHD-osu
  email: yfhdtw@gmail.com

priority: optional
section: x11
installed_size: 20000

dependencies:

essential: false

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - NTUT
  - NTUT Program

generic_name: NTUT Assigiment

categories:
  - Development
  - Utility

startup_notify: true