name: Build Windows

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Set the version number of this build"
        required: true
      
      distro:
        type: choice
        description: Set the distro channel of this build
        required: true
        options: 
        - Alpha
        - Beta
        - Release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkout@v3
        uses: actions/checkout@v3
      
      - name: Install Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
          flutter-version: 3.24.0

      - name: Install dependencies
        run: |
          flutter --version
          flutter config --enable-web
          flutter clean
          flutter pub get
          flutter pub upgrade

      - name: Build Windows
        run:
          flutter build windows -t lib/main.dart --release --dart-define VERSION=${{ github.event.inputs.version }} --dart-define DISTRO=${{ github.event.inputs.distro }}
      
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip the build
        run: zip -r windows_build.zip ./build/windows/x64/runner/Release
        working-directory: ./

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: NTUT_Program_Assigiment_${{ github.event.inputs.version }}_${{ github.event.inputs.distro }}.zip
          path: windows_build.zip
          retention-days: 5